--INSERT INTO select_one (one_first_times, one_second_times, one_third_times, select_one_date, category) VALUES ('1', '1', '1', '2018-01-01', '1');
INSERT INTO push_one (push_id, push_name) VALUES ('1', '観海寺温泉');
INSERT INTO push_one (push_id, push_name) VALUES ('2','Beppu');
INSERT INTO push_one (push_id, push_name) VALUES ('3', 'Hamawaki');
INSERT INTO push_one (push_id, push_name) VALUES ('4', 'Kannawa');
INSERT INTO push_one (push_id, push_name) VALUES ('5', 'Myouban');
INSERT INTO push_one (push_id, push_name) VALUES ('6', 'Kamekawa');
INSERT INTO push_one (push_id, push_name) VALUES ('7', 'Siraisi');
INSERT INTO push_one (push_id, push_name) VALUES ('8', 'Hotta');
INSERT INTO push_one (push_id, push_name) VALUES ('9', 'NotFound');